arrowParens: "always"
bracketSameLine: true
bracketSpacing: true
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
filepath: undefined
htmlWhitespaceSensitivity: "css"
insertPragma: false
jsxBracketSameLine: true
jsxSingleQuote: true
printWidth: 120
proseWrap: "preserve"
quoteProps: "as-needed"
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "none"
useTabs: false